"use client";
import localFont from "next/font/local";
import "./globals.css";
import ResponsiveAppBar from "./component/HeaderSection";
import { ThemeProvider, createTheme } from "@mui/material/styles"; // Import ThemeProvider and createTheme

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Create a theme (optional, can customize as needed)
const theme = createTheme();

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider theme={theme}> {/* Wrap your application in ThemeProvider */}
          <ResponsiveAppBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
